### ISSUE TITLE
How to understand mutation like "H:D100aD,H:D100bQ,H:S100cR,H:P100dR,H:Q100eY"?

### ISSUE THREAD

**Issue by xueeinstein** [sarahsirin/AB-Bind-Database#2]
It's easy to understand a replacement mutation representing by "H:D100Q", but how to understand mutation like "H:D100aD,H:D100bQ,H:S100cR,H:P100dR,H:Q100eY"?

**Comment by sarahsirin** [comment]
This has to do with the CDR numbering scheme. For long CDRH3, such as the example here, this numbering scheme is applied in order to ensure that framework residue numbers can be aligned.  

IMGT website could be a good source for you to get more info on antibody numbering scheme.  http://www.imgt.org/IMGTScientificChart/Numbering/IMGTIGVLsuperfamily.html

**Comment by xueeinstein** [comment]
Thanks for your reply! It's very helpful!
